#!/bin/sh

SETTINGS=$HOME/.ZimReader

if [ ! -f $SETTINGS ]
then
    echo "[ZimReader]
port=8080
localonly=x
directory=." >$SETTINGS

fi

getval () {
  var=$1
  def=$2
  val=`awk 'BEGIN { FS="=" } $1 == "'$var'" { print $2 }' $SETTINGS 2>/dev/null`
  [ "$val" ] || val=$def
  echo $val
}

port=`getval port 8000`
localonly=`getval localonly`
directory=`getval directory .`

while true
  do
    echo -en "


    ZimReader
    =========

    1)\tVerzeichnis:    $directory
    2)\tPort:           $port
    8)\t[$localonly] nur auf Anfragen vom lokalen Rechner antworten

    9)\tEinstellungen speichern
    X)\tEnde

    Ihre Auswahl: "

    read CH

    case $CH in
        1)
            echo -n "Verzeichnis: "
            read n
            [ "$n" ] && directory=$n
            ;;

        2)
            echo -n "Port: "
            read n
            [ "$n" ] && port=$n
            ;;

        8)
            if [ -z "$localonly" ]
              then
                localonly='x'
              else
                localonly=
            fi
            ;;

        9)
            echo "[ZimReader]
port=$port
localonly=$localonly
directory=$directory
" >$SETTINGS
            echo
            echo "

*** Die Einstellungen wurden gespeichert

"
            ;;

        x|X)
            exit
    esac
  done
